AccountingSoftware/Areas/Administrator/Controllers/BaoCaoBangLuongTongHopController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AccountingSoftware.Models;

namespace AccountingSoftware.Areas.Administrator.Controllers
{
    public class BaoCaoBangLuongTongHopController : Controller
    {
        private AccountingSoftwareDbContext db = new AccountingSoftwareDbContext();

        // GET: Administrator/BaoCaoLuong
        public ActionResult Index(int? manv, string thang, string nam)
        {
            var NhanViens = db.NhanViens.ToList();
            ViewBag.nhanviens = NhanViens;
            var listModel = new List<BaoCaoBangLuong>();
            var listTNCN = db.ThueTNCNs.ToList();
            var parameters = thang + "/" + nam;
            var paramsThamSo = db.ThamSoTinhLuongs.Where(x => x.ThangNam == parameters).FirstOrDefault();
            if (paramsThamSo == null)
            {
                var newModel = new BaoCaoBangLuong();

                return View(newModel);
            }
            else
            {
                var listNhanVien = db.NhanViens.Where(x => x.MaNV == manv).ToList();
                foreach (var item in listNhanVien)
                {
                    var newModel = new BaoCaoBangLuong();
                    var soCong = db.BangChamCongs.Where(x => x.MaNV == item.MaNV).FirstOrDefault();
                    newModel.HoTen = item.HoTen;
                    newModel.LuongThoaThuan = item.LuongThoaThuan;
                    newModel.LuongCoBan = item.LuongCoBan;
                    newModel.CongLuong = paramsThamSo.CongLuong;
                    newModel.SoNgayCongThucTe = soCong.SoNgayCongThucTe;
                    double total1 = double.Parse(item.LuongCoBan) * double.Parse(paramsThamSo.TLBHXH);
                    newModel.BHXH = total1.ToString();
                    double total2 = double.Parse(item.LuongCoBan) * double.Parse(paramsThamSo.TLBHTN);
                    newModel.BHTN = total2.ToString();
                    double total3 = double.Parse(item.LuongCoBan) * double.Parse(paramsThamSo.TLBHYT);
                    newModel.BHYT = total3.ToString();
                    double total6 = double.Parse(item.LuongCoBan) * double.Parse(paramsThamSo.TLKPCD);
                    newModel.KPCD = total6.ToString();
                    double total7 = double.Parse(item.LuongThoaThuan) - double.Parse(paramsThamSo.GiamTruBanThan) - double.Parse(paramsThamSo.GiamTruNPT);
                    newModel.ThuNhapTinhThue = total7.ToString();
                    foreach (var item1 in listTNCN)
                    {
                        var a = double.Parse(item1.Tu);
                        var b = double.Parse(item1.Den);
                        if (total7 >= a && total7 <= b)
                        {
                            newModel.ThueSuat = item1.ThueSuat;
                            double total4 = (double.Parse(item.LuongThoaThuan) - double.Parse(paramsThamSo.GiamTruBanThan) - double.Parse(paramsThamSo.GiamTruNPT)) * double.Parse(item1.ThueSuat);
                            newModel.KhauTruThueTNCN = total4.ToString();
                        }
                    }
                    newModel.DanhGiaHieuQua = soCong.DGHQCN;
                    if (newModel.KhauTruThueTNCN != null)
                    {
                        double total5 = ((double.Parse(item.LuongThoaThuan) / double.Parse(paramsThamSo.CongLuong)) * double.Parse(soCong.SoNgayCongThucTe) - (total1 + total2 + total3) - double.Parse(newModel.KhauTruThueTNCN)) * double.Parse(soCong.DGHQCN);
                        newModel.ThucLinh = total5.ToString();
                    }
                    else if (newModel.KhauTruThueTNCN == null)
                    {
                        newModel.KhauTruThueTNCN = "0";
                        double total5 = ((double.Parse(item.LuongThoaThuan) / double.Parse(paramsThamSo.CongLuong)) * double.Parse(soCong.SoNgayCongThucTe) - (total1 + total2 + total3) - 0) * double.Parse(soCong.DGHQCN);
                        newModel.ThucLinh = total5.ToString();
                    }

                    var listChucVu = db.ChucVus.ToList();
                    foreach (var item1 in listChucVu)
                    {
                        if (item.MaChucVu == item1.MaChucVu)
                            newModel.ChucVu = item1.TenChucVu;
                    }
                    listModel.Add(newModel);
                }
                ViewBag.ListBCBL = listModel;
                return View(ViewBag.ListBCBL);
            }
        }

        [HttpPost]
        [ValidateInput(false)]
        public EmptyResult Export(string GridHtml)
        {
            Response.Clear();
            Response.Buffer = true;
            Response.AddHeader("content-disposition", "attachment;filename=BaoCaoBangLuongTongHop.doc");
            Response.Charset = "";
            Response.ContentType = "application/vnd.ms-word";
            Response.Output.Write(GridHtml);
            Response.Flush();
            Response.End();
            return new EmptyResult();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AccountingSoftware/Areas/Administrator/Views/BaoCaoBangLuongTongHop/Index.cshtml
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "Báo cáo bảng lương tổng hợp";
}

<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="page-title">
        <div class="title_left">
            <h3>@ViewBag.Title</h3>
        </div>
    </div>
    <div class="x_panel">
        <div class="x_content">
            <div class="form-group col-md-12">
                <div class="col-md-6">
                    @using (Html.BeginForm())
                    {
                        <p>
                            Tên nhân viên:
                            <select name="manv" class="form-select" aria-label="Default select example" style="height: 27px">
                                <option selected>--Chọn nhân viên--</option>

                                @foreach (var item1 in ViewBag.NhanViens)
                                {

                                    <option type="text" value="@item1.MaNV" name="@item1.MaNV">@item1.HoTen</option>
                                }
                            </select>

                            &nbsp;
                            &nbsp;
                            &nbsp;
                            &nbsp;
                            Tháng: @*<input type="number" value="" name="Month" min="1" max="12" required />*@
                            <select name="thang" class="form-select" aria-label="Default select example" style="height: 27px">
                                <option selected>--Chọn Tháng--</option>
                                <option type="number" value="1" name="Month">Tháng 1</option>
                                <option type="number" value="2" name="Month">Tháng 2</option>
                                <option type="number" value="3" name="Month">Tháng 3</option>
                                <option type="number" value="4" name="Month">Tháng 4</option>
                                <option type="number" value="5" name="Month">Tháng 5</option>
                                <option type="number" value="6" name="Month">Tháng 6</option>
                                <option type="number" value="7" name="Month">Tháng 7</option>
                                <option type="number" value="8" name="Month">Tháng 8</option>
                                <option type="number" value="9" name="Month">Tháng 9</option>
                                <option type="number" value="10" name="Month">Tháng 10</option>
                                <option type="number" value="11" name="Month">Tháng 11</option>
                                <option type="number" value="12" name="Month">Tháng 12</option>
                            </select>
                            &nbsp;
                            &nbsp;
                            &nbsp;
                            &nbsp;

                            Năm: @*<input type="number" value="" name="Year" required />*@
                            <select name="nam" class="form-select" aria-label="Default select example" style="height: 27px">
                                <option selected>--Chọn Năm--</option>
                                <option type="number" value="2015" name="Year">2015</option>
                                <option type="number" value="2016" name="Year">2016</option>
                                <option type="number" value="2017" name="Year">2017</option>
                                <option type="number" value="2018" name="Year">2018</option>
                                <option type="number" value="2019" name="Year">2019</option>
                                <option type="number" value="2020" name="Year">2020</option>
                                <option type="number" value="2021" name="Year">2021</option>
                                <option type="number" value="2022" name="Year">2022</option>
                                <option type="number" value="2023" name="Year">2023</option>
                                <option type="number" value="2024" name="Year">2024</option>
                                <option type="number" value="2025" name="Year">2025</option>
                                <option type="number" value="2026" name="Year">2026</option>

                            </select>
                            &nbsp;
                            &nbsp;
                            &nbsp;
                            &nbsp;
                            <input type="submit" value="Xem" class="btn btn-primary" />
                        </p>
                    }
                </div>
                <div class="col-md-6">
                    @using (Html.BeginForm("Export", "BaoCaoBangLuongTongHop", FormMethod.Post))
                    {
                        <input type="hidden" name="GridHtml" />
                        <input type="submit" id="btnSubmit" value="Xuất" class="btn btn-primary" />
                    }
                </div>
            </div>
            <div id="Grid">
                <table class="table table-striped table-bordered">
                    <thead style="border: 1px  solid" cellspacing="0" cellpadding="0">
                        <tr style="border: 1px  solid" cellspacing="0" cellpadding="0">
                            <th style="border: 1px  solid" cellspacing="0" cellpadding="0">
                                Nhân viên
                            </th>
                            <th style="border: 1px  solid" cellspacing="0" cellpadding="0">
                                Chức vụ
                            </th>
                            <th style="border: 1px  solid" cellspacing="0" cellpadding="0">
                                Lương thoả thuận
                            </th>
                            <th style="border: 1px  solid" cellspacing="0" cellpadding="0">
                                Lương cơ bản
                            </th>
                            <th style="border: 1px  solid" cellspacing="0" cellpadding="0">
                                Công lương
                            </th>
                            <th style="border: 1px  solid" cellspacing="0" cellpadding="0">
                                Số ngày công thực tế
                            </th>
                            <th style="border: 1px  solid" cellspacing="0" cellpadding="0">
                                BHXH
                            </th>
                            <th style="border: 1px  solid" cellspacing="0" cellpadding="0">
                                BHYT
                            </th>
                            <th style="border: 1px  solid" cellspacing="0" cellpadding="0">
                                BHTN
                            </th>
                            <th style="border: 1px  solid" cellspacing="0" cellpadding="0">
                                KPCĐ
                            </th>
                            <th style="border: 1px  solid" cellspacing="0" cellpadding="0">
                                Khấu trừ thuế TNCN
                            </th>
                            <th style="border: 1px  solid" cellspacing="0" cellpadding="0">
                                Đánh giá hiệu quả
                            </th>
                            <th style="border: 1px  solid" cellspacing="0" cellpadding="0">
                                Thực lĩnh
                            </th>
                        </tr>
                    </thead>
                    @if (ViewBag.ListBCBL != null)
                    {
                        foreach (var item in ViewBag.ListBCBL)
                        {
                            <tbody style="border: 1px  solid" cellspacing="0" cellpadding="0">
                                <tr style="border: 1px  solid" cellspacing="0" cellpadding="0">
                                    <td style="border: 1px  solid" cellspacing="0" cellpadding="0">@item.HoTen</td>
                                    <td style="border: 1px  solid" cellspacing="0" cellpadding="0">
                                        @item.ChucVu
                                    </td>
                                    <td style="border: 1px  solid" cellspacing="0" cellpadding="0">@item.LuongThoaThuan</td>
                                    <td style="border: 1px  solid" cellspacing="0" cellpadding="0">@item.LuongCoBan</td>
                                    <td style="border: 1px  solid" cellspacing="0" cellpadding="0">@item.CongLuong</td>
                                    <td style="border: 1px  solid" cellspacing="0" cellpadding="0">@item.SoNgayCongThucTe</td>
                                    <td style="border: 1px  solid" cellspacing="0" cellpadding="0">@item.BHXH</td>
                                    <td style="border: 1px  solid" cellspacing="0" cellpadding="0">@item.BHYT</td>
                                    <td style="border: 1px  solid" cellspacing="0" cellpadding="0">@item.BHTN</td>
                                    <td style="border: 1px  solid" cellspacing="0" cellpadding="0">@item.KPCD</td>
                                    <td style="border: 1px  solid" cellspacing="0" cellpadding="0">@item.KhauTruThueTNCN</td>
                                    <td style="border: 1px  solid" cellspacing="0" cellpadding="0">@item.DanhGiaHieuQua</td>
                                    <td style="border: 1px  solid" cellspacing="0" cellpadding="0">@String.Format("{0:0,0đ}", item.ThucLinh)</td>

                                </tr>
                            </tbody>
                        }
                    }
                </table>
            </div>
        </div>
</div>
<script>
    $(function () {
        $("#btnSubmit").click(function () {
            $("input[name='GridHtml']").val($("#Grid").html());
        });
    });
</script>