AccountingSoftware/Models/BaoCaoBaoHiemXH.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AccountingSoftware.Models
{
    public class BaoCaoBaoHiemXH
    {
        public int MaNV { get; set; }
        public string HoTen { get; set; }
        public string LuongCoBan { get; set; }
        public string TLBHXH { get; set; }
        public string TLBHYT { get; set; }
        public string TLBHTN { get; set; }

        public string MucChiTraTLBHXH { get; set; }
        public string MucChiTraTLBHYT { get; set; }
        public string MucChiTraTLBHTN { get; set; }
        public string TongTien { get; set; }
    }
}

AccountingSoftware/Areas/Administrator/Controllers/BaoCaoBaoHiemXHController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AccountingSoftware.Models;

namespace AccountingSoftware.Areas.Administrator.Controllers
{
    public class BaoCaoBaoHiemXHController : Controller
    {
        private AccountingSoftwareDbContext db = new AccountingSoftwareDbContext();

        // GET: Administrator/BaoCaoBaoHiemXH
        public ActionResult Index(string thang, string nam)
        {
            var listModel = new List<BaoCaoBaoHiemXH>();

            var parameters = thang + "/" + nam;
            var paramsThamSo = db.ThamSoTinhLuongs.Where(x => x.ThangNam == parameters).FirstOrDefault();
            if (paramsThamSo == null)
            {
                var newModel = new BaoCaoBaoHiemXH();

                return View(newModel);
            }
            else
            {
                var listNhanVien = db.NhanViens.ToList();
                foreach (var item in listNhanVien)
                {
                    var newModel = new BaoCaoBaoHiemXH();
                    newModel.HoTen = item.HoTen;
                    newModel.LuongCoBan = item.LuongCoBan;
                    newModel.TLBHXH = paramsThamSo.TLBHXH;
                    newModel.TLBHTN = paramsThamSo.TLBHTN;
                    newModel.TLBHYT = paramsThamSo.TLBHYT;
                    double total1 = double.Parse(item.LuongCoBan) * double.Parse(paramsThamSo.TLBHXH);
                    newModel.MucChiTraTLBHXH = total1.ToString();
                    double total2 = double.Parse(item.LuongCoBan) * double.Parse(paramsThamSo.TLBHTN);
                    newModel.MucChiTraTLBHTN = total2.ToString();
                    double total3 = double.Parse(item.LuongCoBan) * double.Parse(paramsThamSo.TLBHYT);
                    newModel.MucChiTraTLBHYT = total3.ToString();
                    double total4 = total1 + total2 + total3;
                    newModel.TongTien = total4.ToString();
                    listModel.Add(newModel);
                }
                ViewBag.ListBhxh = listModel;
                return View(ViewBag.ListBhxh);
            }
        }

        [HttpPost]
        [ValidateInput(false)]
        public EmptyResult Export(string GridHtml)
        {
            Response.Clear();
            Response.Buffer = true;
            Response.AddHeader("content-disposition", "attachment;filename= BaoCaoBaoHiemXaHoi.doc");
            Response.Charset = "";
            Response.ContentType = "application/vnd.ms-word";
            Response.Output.Write(GridHtml);
            Response.Flush();
            Response.End();
            return new EmptyResult();
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AccountingSoftware/Areas/Administrator/Views/BaoCaoBaoHiemXH/Index.cshtml
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "Báo cáo khoản trích theo lương";
}

<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="page-title">
        <div class="title_left">
            <h3>@ViewBag.Title</h3>
        </div>
    </div>
    <div class="x_panel">
        <div class="x_content">
            <div class="form-group col-md-12">
                <div class="col-md-6">
                    @using (Html.BeginForm())
                    {
                        <p>
                            Tháng: @*<input type="number" value="" name="Month" min="1" max="12" required />*@
                            <select name="thang" class="form-select" aria-label="Default select example" style="height: 27px">
                                <option selected>--Chọn Tháng--</option>
                                <option type="number" value="1" name="Month">Tháng 1</option>
                                <option type="number" value="2" name="Month">Tháng 2</option>
                                <option type="number" value="3" name="Month">Tháng 3</option>
                                <option type="number" value="4" name="Month">Tháng 4</option>
                                <option type="number" value="5" name="Month">Tháng 5</option>
                                <option type="number" value="6" name="Month">Tháng 6</option>
                                <option type="number" value="7" name="Month">Tháng 7</option>
                                <option type="number" value="8" name="Month">Tháng 8</option>
                                <option type="number" value="9" name="Month">Tháng 9</option>
                                <option type="number" value="10" name="Month">Tháng 10</option>
                                <option type="number" value="11" name="Month">Tháng 11</option>
                                <option type="number" value="12" name="Month">Tháng 12</option>
                            </select>
                            &nbsp;
                            &nbsp;
                            &nbsp;
                            &nbsp;

                            Năm: @*<input type="number" value="" name="Year" required />*@
                            <select name="nam" class="form-select" aria-label="Default select example" style="height: 27px">
                                <option selected>--Chọn Năm--</option>
                                <option type="number" value="2015" name="Year">2015</option>
                                <option type="number" value="2016" name="Year">2016</option>
                                <option type="number" value="2017" name="Year">2017</option>
                                <option type="number" value="2018" name="Year">2018</option>
                                <option type="number" value="2019" name="Year">2019</option>
                                <option type="number" value="2020" name="Year">2020</option>
                                <option type="number" value="2021" name="Year">2021</option>
                                <option type="number" value="2022" name="Year">2022</option>
                                <option type="number" value="2023" name="Year">2023</option>
                                <option type="number" value="2024" name="Year">2024</option>
                                <option type="number" value="2025" name="Year">2025</option>
                                <option type="number" value="2026" name="Year">2026</option>

                            </select>
                            &nbsp;
                            &nbsp;
                            &nbsp;
                            &nbsp;
                            <input type="submit" value="Xem" class="btn btn-primary" />
                        </p>
                    }
                </div>
                <div class="col-md-6">
                    @using (Html.BeginForm("Export", "BaoCaoBaoHiemXH", FormMethod.Post))
                    {
                        <input type="hidden" name="GridHtml" />
                        <input type="submit" id="btnSubmit" value="Xuất" class="btn btn-primary" />
                    }
                </div>
            </div>
            <div id="Grid">
                <table class="table table-striped table-bordered">
                    <thead>
                        <tr style="border: 1px  solid" cellspacing="0" cellpadding="0">
                            <th style="border: 1px  solid" cellspacing="0" cellpadding="0">
                                Nhân viên
                            </th>
                            <th style="border: 1px  solid" cellspacing="0" cellpadding="0">
                                Lương tính bảo hiểm
                            </th>
                            <th style="border: 1px  solid" cellspacing="0" cellpadding="0">
                                BHXH
                            </th>
                            <th style="border: 1px  solid" cellspacing="0" cellpadding="0">
                                BHYT
                            </th>
                            <th style="border: 1px  solid" cellspacing="0" cellpadding="0">
                                BHTN
                            </th>
                            <th style="border: 1px  solid" cellspacing="0" cellpadding="0">
                                Mức chi trả BHXH
                            </th>
                            <th style="border: 1px  solid" cellspacing="0" cellpadding="0">
                                Mức chi trả BHYT
                            </th>
                            <th style="border: 1px  solid" cellspacing="0" cellpadding="0">
                                Mức chi trả BHTN
                            </th>
                            <th style="border: 1px  solid" cellspacing="0" cellpadding="0">
                                Tổng tiền
                            </th>
                        </tr>
                    </thead>
                    @if (ViewBag.ListBhxh != null)
                    {
                        foreach (var item in ViewBag.ListBhxh)
                        {
                            <tbody style="border: 1px  solid" cellspacing="0" cellpadding="0">
                                <tr style="border: 1px  solid" cellspacing="0" cellpadding="0">
                                    <td style="border: 1px  solid" cellspacing="0" cellpadding="0">@item.HoTen</td>
                                    <td style="border: 1px  solid" cellspacing="0" cellpadding="0">
                                        @String.Format("{0:0,0đ}", item.LuongCoBan)
                                    </td>
                                    <td style="border: 1px  solid" cellspacing="0" cellpadding="0">@item.TLBHXH</td>
                                    <td style="border: 1px  solid" cellspacing="0" cellpadding="0">@item.TLBHYT</td>
                                    <td style="border: 1px  solid" cellspacing="0" cellpadding="0">@item.TLBHTN</td>
                                    <td style="border: 1px  solid" cellspacing="0" cellpadding="0">@String.Format("{0:0,0đ}", item.MucChiTraTLBHXH)</td>
                                    <td style="border: 1px  solid" cellspacing="0" cellpadding="0">@String.Format("{0:0,0đ}", item.MucChiTraTLBHYT)</td>
                                    <td style="border: 1px  solid" cellspacing="0" cellpadding="0">@String.Format("{0:0,0đ}", item.MucChiTraTLBHTN)</td>
                                    <td style="border: 1px  solid" cellspacing="0" cellpadding="0">@String.Format("{0:0,0đ}", item.TongTien)</td>
                                </tr>
                            </tbody>
                        }
                    }
                </table>
            </div>
        </div>
</div>
<script>
    $(function () {
        $("#btnSubmit").click(function () {
            $("input[name='GridHtml']").val($("#Grid").html());
        });
    });
</script>